name: Build
description: Build adminer image
inputs:
  version:
    description: version
    required: true
  tags:
    description: image tags
    required: true
  alpine_ver:
    description: alpine version
    required: true
  platform:
    description: docker platform
    required: false
    default: linux/amd64
runs:
  using: "composite"
  steps:
  - name: Build image
    env:
      ADMINER_VER: ${{ inputs.version }}
      PLATFORM: ${{ inputs.platform }}
      TAGS: ${{ inputs.tags }}
      ALPINE_VER: ${{ inputs.alpine_ver }}
    run: |
      set -e
      make buildx-build-amd64
      make test
      make buildx-build
      . $GITHUB_ACTION_PATH/release.sh
    shell: bash
