name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

env:
  ADMINER5: '5.4.0'

jobs:
  adminer-build:
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push
        env:
          ADMINER_VER: ${{ env.ADMINER5 }}
          ARCH: ${{ matrix.arch }}
        run: |
          make
          make test
          make push
  adminer-push:
    runs-on: ubuntu-latest
    needs:
      - adminer-build
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: ./.github/actions
        with:
          version: ${{ env.ADMINER5 }}
          latest: true
          latest_major: true
